### ISSUE TITLE
Verander <html lang="en"> naar <html lang="nl">

### ISSUE THREAD

**Issue by sannevanseeventer** [Khdulkadir/look-and-feel-living-styleguide#16]
https://github.com/Khdulkadir/look-and-feel-living-styleguide/blob/e33772ea0a572e271ff12d6ea1fdd162458ac965/index.html#L2C1-L2C17

```<html lang="en">``` 

Voor Nederlandse websites gebruik je: ```<html lang="nl">```

**Comment by EBok1** [comment]
Veranderd naar: <html lang="nl">
